.circleci/config.yml
fbcnms-packages/fbcnms-alarms/package.json
yarn.lock

Signed-off-by: Scott8440 <scott8440@gmail.com>
Summary:
I was debugging a problem with a package I'm building that consumes `fbcnms/alarms`. Turns out the package was not being built correctly. Looking into the CI jobs here I noticed that `deploy-fbcnms-alarms` has been failing since the beginning because `babel` was not installed when running `npm publish`. Fix this by running `yarn install` before doing the publish step.
Test Plan:
CI job with manual overrides to trigger running a `--dry-run` npm publish with this updated config:
https://app.circleci.com/pipelines/github/facebookincubator/fbc-js-core/198/workflows/7f57a03b-9ea4-44ef-943d-67674fc0e826/jobs/1801

[ci] Run yarn install before npm publish

---

fbcnms-packages/fbcnms-alarms/package.json
fbcnms-packages/fbcnms-platform-server/package.json

Signed-off-by: Scott8440 <scott8440@gmail.com>

bump axios version

---

fbcnms-packages/fbcnms-alarms/components/Alarms.js
fbcnms-packages/fbcnms-alarms/components/AlertRules.js
fbcnms-packages/fbcnms-alarms/components/SnackbarItem.js
fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/AlertDetailsPane.js
fbcnms-packages/fbcnms-alarms/components/alertmanager/FiringAlerts.js
fbcnms-packages/fbcnms-alarms/components/alertmanager/Receivers/ConfigEditor.js
fbcnms-packages/fbcnms-alarms/components/alertmanager/Receivers/GlobalConfig.js
fbcnms-packages/fbcnms-alarms/components/alertmanager/Receivers/Receivers.js
fbcnms-packages/fbcnms-alarms/components/alertmanager/Routes.js
fbcnms-packages/fbcnms-alarms/components/alertmanager/Suppressions.js
fbcnms-packages/fbcnms-alarms/components/common/Editor.js
fbcnms-packages/fbcnms-alarms/components/rules/AddEditRule.js
fbcnms-packages/fbcnms-alarms/components/rules/PrometheusEditor/PrometheusEditor.js
fbcnms-packages/fbcnms-alarms/components/rules/PrometheusEditor/ToggleableExpressionEditor.js
fbcnms-packages/fbcnms-alarms/components/rules/SelectRuleType.js
fbcnms-packages/fbcnms-alarms/components/severity/SeverityIndicator.js
fbcnms-packages/fbcnms-alarms/components/table/SimpleTable.js
fbcnms-packages/fbcnms-alarms/components/table/TableActionDialog.js
fbcnms-packages/fbcnms-alarms/components/table/TableAddButton.js
fbcnms-packages/fbcnms-alarms/package.json
fbcnms-packages/fbcnms-ui/package.json
flow-typed/npm/@material-ui/core_v1.x.x.js

Signed-off-by: Scott8440 <scott8440@gmail.com>
To fix a security vulnerability of notistack.
Also had to do some small changes to material-ui stuff that was being imported improperly as of 4.0 which was breaking things in the snackbar.
https://github.com/mui-org/material-ui/issues/15976#issuecomment-499774398
Tested by publishing new version to private repo (verdaccio) and running prometheus-configmanager UI with the new package:

[alarms] update notistack version

---

fbcnms-packages/fbcnms-sequelize-models/index.js
fbcnms-packages/fbcnms-sequelize-models/package.json

When `sequelize-models` is configured to use Postgres, incorrect queries are constructed for the equivalent of JSON_CONTAINS. This pull request adds a else-if branch to `jsonArrayContains` function to support the `postgres` sql dialect for sequelize-models.
See (https://github.com/facebookincubator/fbc-js-core/pull/73)
Tested manually using a Magma NMS setup with manually modified dependencies.

Support postgres in sequelize-models

---

fbcnms-packages/fbcnms-express-middleware/package.json
fbcnms-packages/fbcnms-platform-server/package.json

When `sequelize-models` is configured to use Postgres, incorrect queries are constructed for the equivalent of JSON_CONTAINS. This pull request updates `express-middleware` to use the updated version of `sequelize-models` which no longer has this issue. See (https://github.com/facebookincubator/fbc-js-core/pull/72)
Tested manually using a Magma NMS setup with manually modified dependencies.

Support postgres in express-middleware

---

.circleci/config.yml
fbcnms-packages/fbcnms-sequelize-models/README.md
fbcnms-packages/fbcnms-sequelize-models/dbDataMigration.js
fbcnms-packages/fbcnms-sequelize-models/package.json
yarn.lock

Adds a `dbDataMigration` script to `fbcnms/sequelize-models`, intended to be used to sequelize-models data from one DB to another.
This package will be first used for migrating the Magma NMS DB data to share with Magma orc8r DB, allowing network operators to run on a single AWS RDS instance, or allow for other simpler, or cheaper setups. This is intended to be used as a script pre-upgrade from v1.4 to v1.5
**Example: Manual Usage**
```
$ yarn start
? Enter Source DB host: mariadb
? Enter Source DB port: 3306
? Enter Source DB database name: nms
? Enter Source DB username: root
? Enter Source DB password: [hidden]
? Enter Source DB SQL dialect: mariadb
Source DB Connection Config:
---------------------------
Host: mariadb:3306
Database: nms …
```

Add DB data migration script to fbcnms/sequelize-models

---

fbcnms-packages/fbcnms-sequelize-models/README.md
fbcnms-packages/fbcnms-sequelize-models/dbDataMigration.js
fbcnms-packages/fbcnms-sequelize-models/index.js
fbcnms-packages/fbcnms-sequelize-models/package.json

Modifies the `dbDataMigration` script to `fbcnms/sequelize-models`, intended to be used to sequelize-models data from one DB to another. This PR adds ability to either import from the specified DB, or export to the specified DB.
This package will be first used for migrating the Magma NMS DB data to share with Magma orc8r DB, allowing network operators to run on a single AWS RDS instance, or allow for other simpler, or cheaper setups. This is intended to be used as a script pre-upgrade from v1.4 to v1.5
**Example: Manual Usage**
```
$ yarn dbDataMigrate
? Enter DB host: mariadb
? Enter DB port: 3306
? Enter DB database name: nms
? Enter DB username: root
? Enter DB password: [hidden]
? Enter DB SQL dialect: mariadb
DB Connection Config: …
```

Support bidirectional DB data migration in fbcnms-sequelize-models

---

fbcnms-packages/fbcnms-sequelize-models/dbDataMigration.js
fbcnms-packages/fbcnms-sequelize-models/index.js
fbcnms-packages/fbcnms-sequelize-models/package.json

Updated `@fbcnms/sequelize-models` to `0.1.5`
Two bug fixes included in this update:
1. The `tabs` column in the `Organizations` and `Users` table can be null sometimes, despite being specified as non-null in the sequelize models. The data migration methods account for this by providing default values.
2. Method `isMigrationNeeded` always checks the DB specified by the env variables. This has been fixed to check the 'target' DB instead, which may not be the DB specified by env variables. (If migrating from DB 'A' to DB 'B', the 'target' in this case would be 'B')
Please no comments on code being slightly redundant. Refactoring changes to be included in another PR after this is merged.
This PR has been manually tested on a Magma orchestrator/NMS …

[sequelize-models] Fix db data migration mishandling null column values

---

fbcnms-packages/fbcnms-sequelize-models/index.js
fbcnms-packages/fbcnms-sequelize-models/package.json

During DB data migration function through the `sequelize-models` package, the SequelizeMeta table needs to be migrated as well. This table is used by Sequelize to keep track of what sequelize migrations have run, and if this table is not migrated, then the same migrations will re-run, leading to issues.
Tested manually on a k8s setup, verifying that the `SequelizeMeta` table was created, and included all the rows from the original table. Also verified that the sequelize migrations would not re-run.

[sequelize-models] Migrate SequelizeMeta table during db data migration

---

fbcnms-packages/fbcnms-sequelize-models/package.json
yarn.lock

This adds a dependency to `sequelize-models` for `pg`. This is required when connecting to Postgres databases.

[sequelize-models] Add pg dependency

---

fbcnms-packages/fbcnms-sequelize-models/migrations/20210427134100-user-tabs-default.js
fbcnms-packages/fbcnms-sequelize-models/package.json

Fixes a bug where users of the `@fbcnms/sequelize-models` package expect the `tabs` field to be an array, but find it to be a string instead. This changes the default value to avoid this issue.
**Before**:
```
nms=# \d "Users"
Table "public.Users"
Column      |           Type           | Collation | Nullable |               Default
------------------+--------------------------+-----------+----------+-------------------------------------
id               | integer                  |           | not null | nextval('"Users_id_seq"'::regclass)
email            | character varying(255)   |           | not null |
password         | character varying(255)   |           | not null |
role             | integer                  |           | not null | 0 …
```

[sequelize-models] Add migration for new default in Users/tabs

---

fbcnms-packages/fbcnms-express-middleware/package.json
fbcnms-packages/fbcnms-platform-server/package.json

Upgrade version of `@fbcnms/sequelize-models` to `^0.1.7`

Upgrade sequelize-models version to ^0.1.7

---

fbcnms-packages/fbcnms-express-middleware/package.json
fbcnms-packages/fbcnms-platform-server/package.json

Upgrades version dependency of express-middleware and platform-server on sequelize-models to ^0.1.8

Upgrade sequelize-models versions to 0.1.8

---

fbcnms-packages/fbcnms-alarms/package.json
yarn.lock

When syncing code for fbcnms-alarms from internal Facebook repo, the package version was lowered, rather than increased. Additionally, the dependency version of notistack was lowered. This update bumps up the version numbers of both, and will trigger a release of a new version of `@fbcnms/alarms`.

[fbcnms-alarms] Fix version number and notistack version

---

fbcnms-packages/fbcnms-alarms/components/AlarmContext.js
fbcnms-packages/fbcnms-alarms/components/Alarms.js
fbcnms-packages/fbcnms-alarms/components/__tests__/hooks-test.js
fbcnms-packages/fbcnms-alarms/components/hooks.js
fbcnms-packages/fbcnms-alarms/package.json
flow-typed/npm/@material-ui/core_v1.x.x.js
flow-typed/npm/@material-ui/icons_v4.x.x.js

By default, useNetworkId pulls from match.params. This adds a prop to
customize useNetworkId externally. Eventually we'll make the prop
required.
Summary:
Test Plan:
yarn run test
Reviewers:
Subscribers:
Tasks:
Tags:

[fbcnms-alarms] Add getnetworkid param to Alarms

---

fbcnms-packages/fbcnms-alarms/README.md
fbcnms-packages/fbcnms-alarms/package.json
yarn.lock

* adds some docs on using yalc to link the fbcnms-alarms to another repo. This is useful if you want to test the source version of fbcnms-alarms with a local repo.
* add yarn script for local development

[fbcnms-alarms] Add development docs for using yalc. Add a watch script

---

fbcnms-packages/fbcnms-express-middleware/package.json
fbcnms-packages/fbcnms-platform-server/package.json
fbcnms-packages/fbcnms-sequelize-models/index.js
fbcnms-packages/fbcnms-sequelize-models/migrations/20210616000000-pg-set-id-seq.js
fbcnms-packages/fbcnms-sequelize-models/package.json

Package `@fbcnms/sequelize-models` provides a command to migrate model data between databases. This was mainly used to migrate data from MariaDB to Postgres. This feature did not account for resetting the 'id sequence' for each table. As a result, new rows entered into the new tables would re-use IDs, and inserts would fail.
See here for fix explanation on StackOverflow: [link](https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync)
There are two parts to this fix:
1. Sequelize migration
2. Edit to `@fbcnms/sequelize-models` so that for Postgres, 'id sequence' will be reset correctly.
First, checked that the migration runs correctly.
Before migration:
```
nms=# select * from …
```

fix: [sequelize-models] Fix id sequence for tables in Postgres post-db-migration

---

fbcnms-packages/fbcnms-alarms/components/AlarmContext.js
fbcnms-packages/fbcnms-alarms/components/AlarmsApi.js
fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/AlertDetailsPane.js
fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/MetricAlertViewer.js
fbcnms-packages/fbcnms-alarms/components/severity/SeverityIndicator.js
fbcnms-packages/fbcnms-alarms/package.json
fbcnms-packages/fbcnms-alarms/test/testHelpers.js
fbcnms-packages/fbcnms-ui/insights/Alarms/AlarmApi.js

Updated alert detail pane style
Added Chip view option to severity indicator component 
Before : 
After: 
Test Plan:
yarn run test

[fbcnms-alarms] Update alert detail pane style

---

fbcnms-packages/fbcnms-sequelize-models/README.md
fbcnms-packages/fbcnms-sequelize-models/migrations/20210621000000-orgs-name-lowercase.js
fbcnms-packages/fbcnms-sequelize-models/models/organization.js
fbcnms-packages/fbcnms-sequelize-models/package.json

Library `@fbcnms/sequelize-models` has some issues when used with Postgres. To mitigate these issues, stemming from `Sequelize` not handling all the idiosyncrasies of Postgres easily, we are opting to migrate certain strings to be lower case only, such as organization names.
There are two parts to this fix:
1. Sequelize migration to migrate all existing organization names to lower case
2. `Organization` sequelize model will get a creation hook to enforce all newly created organizations have lower case names
Tested creating an organization on the NMS with capital letters, and verified that the created organization only had lower case letters
First, creating some organizations with upper case names
```
MariaDB [nms]> select id, name from …
```

fix: [sequelize-models] Migrate all organizations to be lower case

---

fbcnms-packages/fbcnms-alarms/package.json
yarn.lock

This PR updates `@fbcnms/alarms` to `0.3.1`, upgrading its dependency `@fbcnms/ui` to `0.2.0`
This is part of a series of PRs to remove any Magma-dependent code from fbc-js-core, so that all packages will be more easily reusable between FBC-derived projects, including Magma.
Sanity test from running unit tests:
```
➜  fbc-js-core git:(platform-rm-magma) yarn run test
```

chore(alarms): Upgrade version of fbcnms-ui to 0.2.0

---

.circleci/config.yml
fbcnms-packages/fbcnms-auth/package.json
yarn.lock

yarn install fails on the main branch due to an outdated sqlite3 dependency.

Node gyp circleci fix

---

fbcnms-packages/fbcnms-auth/package.json
yarn.lock

Fixes https://github.com/facebookincubator/fbc-js-core/issues/137
I tested by running unit tests. They passed. However caution is warranted because I am upgrading a package used here by 3 major versions.

chore: update openid-client to 5.1.0

---

fbcnms-packages/fbcnms-auth/package.json
yarn.lock

This fixes CI failure and enables other upgrades to be published to npm.

Downgrade openid-client to 2.4.5.

---

fbcnms-packages/fbcnms-platform-server/package.json
fbcnms-packages/fbcnms-sequelize-models/package.json
yarn.lock

chore: upgrade sequelize to latest to pick up validator upgrade
Closes https://github.com/ospoco/magma-issue-tracker/issues/23. A replacement for now-closed PR https://github.com/facebookincubator/fbc-js-core/pull/145 for the sake of providing cleaner history.  
Note upgrade from 5.x.x to 6.x.x, which should be a breaking change but didn't trigger test failures.

chore: upgrade sequelize to latest to pick up validator upgrade

---

fbcnms-packages/fbcnms-platform-server/package.json
fbcnms-packages/fbcnms-sequelize-models/package.json
yarn.lock

chore: switch sequelize from 6.12.2 to last 5.x version to fix Magma unit test
This fixes a SQL error in a Magma unit test given the current version of sequelize. In the future there should exist a unit test in fbc-js-core to catch that problem.
Because of the complex package structure in fbc-js-core, the best way to verify this will fix the Magma unit test is to push this change in fbc-js-core. With regard to downstream consumers of fbc-js-core this change is low-risk. 

chore: switch sequelize from 6.12.2 to last 5.x version to fix Magma unit test

---

fbcnms-packages/fbcnms-alarms/components/rules/LabelsEditor.js
fbcnms-packages/fbcnms-alarms/components/rules/__tests__/LabelsEditor-test.js
fbcnms-packages/fbcnms-alarms/package.json
package.json

Summary:
spaces in the label name cause issues with the config manager
Test Plan:
yarn run test --watch
Reviewers:
andreilee
Subscribers:
Tasks:
T101473711
Tags:

fix(alarms): remove spaces from label name

---

fbcnms-packages/fbcnms-ui/components/auth/EditUserDialog.js
fbcnms-packages/fbcnms-ui/components/design-system/Button.js
fbcnms-packages/fbcnms-ui/components/design-system/FormField/FormField.js
fbcnms-packages/fbcnms-ui/master/OrganizationDialog.js
fbcnms-packages/fbcnms-ui/master/OrganizationInfoDialog.js
fbcnms-packages/fbcnms-ui/master/OrganizationUserDialog.js
fbcnms-packages/fbcnms-ui/master/Organizations.js
fbcnms-packages/fbcnms-ui/theme/default.js

Add Organization create dialog.
Updated Dialog, FormField and Button style.
The user can click on Add Organization button to display the add organization dialog. The first tab is used to fill the new organization info and the second tab is used to create a user that belongs to the new organization.

feat(fbcnms-ui): Add Organization create

---

fbcnms-packages/fbcnms-auth/package.json
fbcnms-packages/fbcnms-auth/strategies/OrganizationSamlStrategy.js
fbcnms-packages/fbcnms-platform-server/package.json
yarn.lock

Fixes https://github.com/facebookincubator/fbc-js-core/issues/168
See https://github.com/magma/security/issues/14#issuecomment-1045433441
Tested with `yarn run flow` and `yarn run test`. Four unit tests are failing, but they fail on the main branch as well - there are no new fails.

bug: cannot-resolve-module multiSamlStrategy

---

fbcnms-packages/fbcnms-alarms/components/AlertRules.js
fbcnms-packages/fbcnms-alarms/components/table/SimpleTable.js

Summary:
Clicking a row's actions menu on the alert rules page positioned the
popover at the topleft of the screen. The issue is that columns were
recreated after clicking, causing the anchorEl to be destroyed. The
solution was to memoize the column definitions.
Test Plan:
screenshots
Reviewers:
andreilee

fix(alarms): alertrules actions menu popover positioning

---

fbcnms-packages/fbcnms-alarms/package.json
fbcnms-packages/fbcnms-ui/host/Organizations.js
fbcnms-packages/fbcnms-ui/package.json

Updates `@fbcnms/fbcnms-ui` to version `2.0.0` and it now accesses organizations at `/host/organization/..` instead of `/master/organization/..`.

feat(fbcnms-ui): Complete transition from 'master' to 'host'

---

fbcnms-packages/fbcnms-ui/components/ProfileButton.js
fbcnms-packages/fbcnms-ui/hooks/useRouter.js
fbcnms-packages/fbcnms-ui/package.json

Several import errors were observed, and fixed in package `@fbcnms/ui`, including the following:
```
magmalte_1     | WARNING in /usr/src/node_modules/@fbcnms/alarms/node_modules/@fbcnms/ui/hooks/useRouter.js 28:16-29
magmalte_1     | "export 'useRouteMatch' was not found in 'react-router'
magmalte_1     |  @ /usr/src/node_modules/@fbcnms/alarms/components/Alarms.js
magmalte_1     |  @ ./app/components/insights/alarms/Alarms.js
magmalte_1     |  @ ./app/components/cwf/CWFSections.js
magmalte_1     |  @ ./app/components/layout/useSections.js
magmalte_1     |  @ ./app/components/layout/SectionLinks.js
magmalte_1     |  @ ./app/components/main/Index.js
magmalte_1     |  @ ./app/components/Main.js
magmalte_1     |  @ ./app/main.js
```
These were …

fix(fbcnms-ui): Fix imports from react-router to react-router-dom

---

fbcnms-packages/fbcnms-alarms/package.json

Updates the dependency of `@fbcnms/ui` from `2.0.0` to `2.0.1`. See #174

fix(fbcnms-alarms): Fix imports from react-router to react-router-dom

---

fbcnms-packages/fbcnms-alarms/components/Alarms.js
fbcnms-packages/fbcnms-alarms/package.json

- bumped version of `@fbcnms/alarms` to `1.0.5`
- Fixed call of `matchParam` function imported from `react-router`

fix(fbcnms-alarms): Fix call to matchParam of react-router

---

fbcnms-packages/fbcnms-express-middleware/package.json
fbcnms-packages/fbcnms-platform-server/package.json

`@fbcnms/express-middleware` was not resolving to the correct version of `@fbcnms/sequelize-models`

fix(express-middleware): Bump version to 0.2.0 for master->host
